---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/store_buys":
    post:
      summary: Register a bought try
      tags:
      - Store Buys
      parameters: []
      responses:
        '201':
          description: store buy created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                credit_card:
                  type: object
                  properties:
                    date:
                      type: string
                    number:
                      type: string
                    security_number:
                      type: string
                  required:
                  - date
                  - number
                  - security_number
                partner_store:
                  type: object
                  properties:
                    times:
                      type: integer
                    price:
                      type: integer
                    machine_key:
                      type: string
                  required:
                  - times
                  - price
                  - machine_key
              required:
              - credit_card
              - partner_store
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
